In [1]:
import numpy as np
import pandas as pd

In [2]:
data= pd.read_csv("D:/DS projects/fraud detection/Data.csv")
pd.set_option("display.max_columns", None)

In [3]:
data.head()

,Unnamed: 0,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud
0,0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,Uber,US,US,2.0,1.0,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
1,1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,AMC #191138,US,US,9.0,1.0,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,True,NaN,NaN,False,False
2,2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
3,3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False,False
4,4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,2.0,1.0,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,NaN,0.0,NaN,NaN,NaN,True,NaN,NaN,False,False

In [4]:
data.shape

(786363, 30)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786363 entries, 0 to 786362
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                786363 non-null  int64
 1   accountNumber             786363 non-null  int64
 2   customerId                786363 non-null  int64
 3   creditLimit               786363 non-null  int64
 4   availableMoney            786363 non-null  float64
 5   transactionDateTime       786363 non-null  object
 6   transactionAmount         786363 non-null  float64
 7   merchantName              786363 non-null  object
 8   acqCountry                781801 non-null  object
 9   merchantCountryCode       785639 non-null  object
 10  posEntryMode              782309 non-null  float64
 11  posConditionCode          785954 non-null  float64
 12  merchantCategoryCode      786363 non-null  object
 13  currentExpDate            786363 non-null  object
 14  accountOpenDate           786363 non-null  object
 15  dateOfLastAddressChange   786363 non-null  object
 16  cardCVV                   786363 non-null  int64
 17  enteredCVV                786363 non-null  int64
 18  cardLast4Digits           786363 non-null  int64
 19  transactionType           785665 non-null  object
 20  echoBuffer                0 non-null       float64
 21  currentBalance            786363 non-null  float64
 22  merchantCity              0 non-null       float64
 23  merchantState             0 non-null       float64
 24  merchantZip               0 non-null       float64
 25  cardPresent               786363 non-null  bool
 26  posOnPremises             0 non-null       float64
 27  recurringAuthInd          0 non-null       float64
 28  expirationDateKeyInMatch  786363 non-null  bool
 29  isFraud                   786363 non-null  bool
dtypes: bool(3), float64(11), int64(7), object(9)
memory usage: 164.2+ MB

In [6]:
data.isnull().sum()

Unnamed: 0                       0
accountNumber                    0
customerId                       0
creditLimit                      0
availableMoney                   0
transactionDateTime              0
transactionAmount                0
merchantName                     0
acqCountry                    4562
merchantCountryCode            724
posEntryMode                  4054
posConditionCode               409
merchantCategoryCode             0
currentExpDate                   0
accountOpenDate                  0
dateOfLastAddressChange          0
cardCVV                          0
enteredCVV                       0
cardLast4Digits                  0
transactionType                698
echoBuffer                  786363
currentBalance                   0
merchantCity                786363
merchantState               786363
merchantZip                 786363
cardPresent                      0
posOnPremises               786363
recurringAuthInd            786363
expirationDateKeyInMatch         0
isFraud                          0
dtype: int64

In [7]:
data.drop(["echoBuffer","merchantCity","merchantState","posOnPremises","recurringAuthInd","merchantZip"],axis=1, inplace=True)

In [8]:
data.head()

,Unnamed: 0,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud
0,0,737265056,737265056,5000,5000.0,2016-08-13T14:27:32,98.55,Uber,US,US,2.0,1.0,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,0.0,False,False,False
1,1,737265056,737265056,5000,5000.0,2016-10-11T05:05:54,74.51,AMC #191138,US,US,9.0,1.0,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,True,False,False
2,2,737265056,737265056,5000,5000.0,2016-11-08T09:18:39,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
3,3,737265056,737265056,5000,5000.0,2016-12-10T02:14:50,7.47,Play Store,US,US,9.0,1.0,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,0.0,False,False,False
4,4,830329091,830329091,5000,5000.0,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,2.0,1.0,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,0.0,True,False,False

In [9]:
data.dropna(inplace = True)

In [10]:
data.isnull().sum()

Unnamed: 0                  0
accountNumber               0
customerId                  0
creditLimit                 0
availableMoney              0
transactionDateTime         0
transactionAmount           0
merchantName                0
acqCountry                  0
merchantCountryCode         0
posEntryMode                0
posConditionCode            0
merchantCategoryCode        0
currentExpDate              0
accountOpenDate             0
dateOfLastAddressChange     0
cardCVV                     0
enteredCVV                  0
cardLast4Digits             0
transactionType             0
currentBalance              0
cardPresent                 0
expirationDateKeyInMatch    0
isFraud                     0
dtype: int64

In [11]:
data.merchantCountryCode.unique()

array(['US', 'CAN', 'PR', 'MEX'], dtype=object)

In [12]:
data.merchantCategoryCode.unique()

array(['rideshare', 'entertainment', 'mobileapps', 'fastfood',
       'food_delivery', 'auto', 'online_retail', 'gym', 'health',
       'personal care', 'food', 'fuel', 'online_subscriptions',
       'online_gifts', 'hotels', 'airline', 'furniture', 'subscriptions',
       'cable/phone'], dtype=object)

In [13]:
data['transactionDateTime'] = pd.to_datetime(data['transactionDateTime'])
data['dateOfLastAddressChange'] = pd.to_datetime(data['dateOfLastAddressChange'])
data['accountOpenDate'] = pd.to_datetime(data['accountOpenDate'])
data['currentExpDate'] = pd.to_datetime(data['currentExpDate'])

In [14]:
data.drop(["merchantName"],axis=1,inplace=True)

In [15]:
data=pd.get_dummies(data,drop_first=True)

In [16]:
data.drop(["Unnamed: 0"],axis=1,inplace=True)

In [17]:
data.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,posEntryMode,posConditionCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,acqCountry_MEX,acqCountry_PR,acqCountry_US,merchantCountryCode_MEX,merchantCountryCode_PR,merchantCountryCode_US,merchantCategoryCode_auto,merchantCategoryCode_cable/phone,merchantCategoryCode_entertainment,merchantCategoryCode_fastfood,merchantCategoryCode_food,merchantCategoryCode_food_delivery,merchantCategoryCode_fuel,merchantCategoryCode_furniture,merchantCategoryCode_gym,merchantCategoryCode_health,merchantCategoryCode_hotels,merchantCategoryCode_mobileapps,merchantCategoryCode_online_gifts,merchantCategoryCode_online_retail,merchantCategoryCode_online_subscriptions,merchantCategoryCode_personal care,merchantCategoryCode_rideshare,merchantCategoryCode_subscriptions,transactionType_PURCHASE,transactionType_REVERSAL
0,737265056,737265056,5000,5000.0,2016-08-13 14:27:32,98.55,2.0,1.0,2023-06-01,2015-03-14,2015-03-14,414,414,1803,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
1,737265056,737265056,5000,5000.0,2016-10-11 05:05:54,74.51,9.0,1.0,2024-02-01,2015-03-14,2015-03-14,486,486,767,0.0,True,False,False,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,737265056,737265056,5000,5000.0,2016-11-08 09:18:39,7.47,9.0,1.0,2025-08-01,2015-03-14,2015-03-14,486,486,767,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
3,737265056,737265056,5000,5000.0,2016-12-10 02:14:50,7.47,9.0,1.0,2025-08-01,2015-03-14,2015-03-14,486,486,767,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0
4,830329091,830329091,5000,5000.0,2016-03-24 21:04:46,71.18,2.0,1.0,2029-10-01,2015-08-06,2015-08-06,885,885,3143,0.0,True,False,False,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [18]:
data["transaction_day"]= pd.to_datetime(data.transactionDateTime,format="%Y/%m/%d").dt.day
data["transaction_month"]= pd.to_datetime(data.transactionDateTime,format="%Y/%m/%d").dt.month
data["transaction_year"]= pd.to_datetime(data.transactionDateTime,format="%Y/%m/%d").dt.year
data["transaction_hour"]= pd.to_datetime(data.transactionDateTime,format="%Y/%m/%d").dt.hour
data["transaction_minute"]= pd.to_datetime(data.transactionDateTime,format="%Y/%m/%d").dt.minute

In [19]:
data.drop(["transactionDateTime"],axis=1,inplace=True)

In [20]:
data["expiry year"]= pd.to_datetime(data.currentExpDate,format="%Y/%m/%d").dt.year
data["expiry month"]= pd.to_datetime(data.currentExpDate,format="%Y/%m/%d").dt.month

In [21]:
data.drop(["currentExpDate"],axis=1,inplace=True)

In [22]:
data["accountopen year"]= pd.to_datetime(data.accountOpenDate,format="%Y/%m/%d").dt.year
data["accountopen month"]= pd.to_datetime(data.accountOpenDate,format="%Y/%m/%d").dt.month
data["accountopen day"]= pd.to_datetime(data.accountOpenDate,format="%Y/%m/%d").dt.day

In [23]:
data.drop(["accountOpenDate"],axis=1,inplace=True)

In [24]:
data["last_address_change year"]= pd.to_datetime(data.dateOfLastAddressChange,format="%Y/%m/%d").dt.year
data["last_address_change month"]= pd.to_datetime(data.dateOfLastAddressChange,format="%Y/%m/%d").dt.month
data["last_address_change day"]= pd.to_datetime(data.dateOfLastAddressChange,format="%Y/%m/%d").dt.day

In [25]:
data.drop(["dateOfLastAddressChange"],axis=1,inplace=True)

In [26]:
data.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionAmount,posEntryMode,posConditionCode,cardCVV,enteredCVV,cardLast4Digits,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,acqCountry_MEX,acqCountry_PR,acqCountry_US,merchantCountryCode_MEX,merchantCountryCode_PR,merchantCountryCode_US,merchantCategoryCode_auto,merchantCategoryCode_cable/phone,merchantCategoryCode_entertainment,merchantCategoryCode_fastfood,merchantCategoryCode_food,merchantCategoryCode_food_delivery,merchantCategoryCode_fuel,merchantCategoryCode_furniture,merchantCategoryCode_gym,merchantCategoryCode_health,merchantCategoryCode_hotels,merchantCategoryCode_mobileapps,merchantCategoryCode_online_gifts,merchantCategoryCode_online_retail,merchantCategoryCode_online_subscriptions,merchantCategoryCode_personal care,merchantCategoryCode_rideshare,merchantCategoryCode_subscriptions,transactionType_PURCHASE,transactionType_REVERSAL,transaction_day,transaction_month,transaction_year,transaction_hour,transaction_minute,expiry year,expiry month,accountopen year,accountopen month,accountopen day,last_address_change year,last_address_change month,last_address_change day
0,737265056,737265056,5000,5000.0,98.55,2.0,1.0,414,414,1803,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,13,8,2016,14,27,2023,6,2015,3,14,2015,3,14
1,737265056,737265056,5000,5000.0,74.51,9.0,1.0,486,486,767,0.0,True,False,False,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,11,10,2016,5,5,2024,2,2015,3,14,2015,3,14
2,737265056,737265056,5000,5000.0,7.47,9.0,1.0,486,486,767,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,8,11,2016,9,18,2025,8,2015,3,14,2015,3,14
3,737265056,737265056,5000,5000.0,7.47,9.0,1.0,486,486,767,0.0,False,False,False,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,10,12,2016,2,14,2025,8,2015,3,14,2015,3,14
4,830329091,830329091,5000,5000.0,71.18,2.0,1.0,885,885,3143,0.0,True,False,False,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,24,3,2016,21,4,2029,10,2015,8,6,2015,8,6

In [27]:
data.columns

Index(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionAmount', 'posEntryMode', 'posConditionCode', 'cardCVV',
       'enteredCVV', 'cardLast4Digits', 'currentBalance', 'cardPresent',
       'expirationDateKeyInMatch', 'isFraud', 'acqCountry_MEX',
       'acqCountry_PR', 'acqCountry_US', 'merchantCountryCode_MEX',
       'merchantCountryCode_PR', 'merchantCountryCode_US',
       'merchantCategoryCode_auto', 'merchantCategoryCode_cable/phone',
       'merchantCategoryCode_entertainment', 'merchantCategoryCode_fastfood',
       'merchantCategoryCode_food', 'merchantCategoryCode_food_delivery',
       'merchantCategoryCode_fuel', 'merchantCategoryCode_furniture',
       'merchantCategoryCode_gym', 'merchantCategoryCode_health',
       'merchantCategoryCode_hotels', 'merchantCategoryCode_mobileapps',
       'merchantCategoryCode_online_gifts',
       'merchantCategoryCode_online_retail',
       'merchantCategoryCode_online_subscriptions',
       'merchantCategoryCode_personal care', 'merchantCategoryCode_rideshare',
       'merchantCategoryCode_subscriptions', 'transactionType_PURCHASE',
       'transactionType_REVERSAL', 'transaction_day', 'transaction_month',
       'transaction_year', 'transaction_hour', 'transaction_minute',
       'expiry year', 'expiry month', 'accountopen year', 'accountopen month',
       'accountopen day', 'last_address_change year',
       'last_address_change month', 'last_address_change day'],
      dtype='object')

In [28]:
X=data[['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionAmount', 'posEntryMode', 'posConditionCode', 'cardCVV',
       'enteredCVV', 'cardLast4Digits', 'currentBalance', 'cardPresent',
       'expirationDateKeyInMatch', 'acqCountry_MEX',
       'acqCountry_PR', 'acqCountry_US', 'merchantCountryCode_MEX',
       'merchantCountryCode_PR', 'merchantCountryCode_US',
       'merchantCategoryCode_auto', 'merchantCategoryCode_cable/phone',
       'merchantCategoryCode_entertainment', 'merchantCategoryCode_fastfood',
       'merchantCategoryCode_food', 'merchantCategoryCode_food_delivery',
       'merchantCategoryCode_fuel', 'merchantCategoryCode_furniture',
       'merchantCategoryCode_gym', 'merchantCategoryCode_health',
       'merchantCategoryCode_hotels', 'merchantCategoryCode_mobileapps',
       'merchantCategoryCode_online_gifts',
       'merchantCategoryCode_online_retail',
       'merchantCategoryCode_online_subscriptions',
       'merchantCategoryCode_personal care', 'merchantCategoryCode_rideshare',
       'merchantCategoryCode_subscriptions', 'transactionType_PURCHASE',
       'transactionType_REVERSAL', 'transaction_day', 'transaction_month',
       'transaction_year', 'transaction_hour', 'transaction_minute',
       'expiry year', 'expiry month', 'accountopen year', 'accountopen month',
       'accountopen day', 'last_address_change year',
       'last_address_change month', 'last_address_change day']]
y=data['isFraud']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,test_size=0.2,random_state=5)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
rf_predict = rf.predict(X_test)
rf_conf_matrix = confusion_matrix(y_test, rf_predict)
rf_acc_score = accuracy_score(y_test, rf_predict)
print("confussion matrix")
print(rf_conf_matrix)
print("-------------------------------------------")
print("Accuracy of Random Forest Classifier:",rf_acc_score*100,'\n')
print("-------------------------------------------")
print(classification_report(y_test,rf_predict))

confussion matrix
[[152884      8]
 [  2399     43]]
-------------------------------------------
Accuracy of Random Forest Classifier: 98.45043583503933

-------------------------------------------
              precision    recall  f1-score   support

       False       0.98      1.00      0.99    152892
        True       0.84      0.02      0.03      2442

    accuracy                           0.98    155334
   macro avg       0.91      0.51      0.51    155334
weighted avg       0.98      0.98      0.98    155334

In [33]:
dframe=pd.DataFrame({'actual':y_test,'Predicted':rf_predict})
dframe.head(50)

        actual  Predicted
267745   False      False
248147   False      False
651180   False      False
733323   False      False
64424    False      False
562822   False      False
645845   False      False
633902   False      False
422442   False      False
598321   False      False
587577   False      False
600222   False      False
766872   False      False
753619   False      False
535643   False      False
390527   False      False
213555   False      False
763649   False      False
285832   False      False
299346   False      False
453427   False      False
192629   False      False
551100   False      False
478704   False      False
569262   False      False
418080   False      False
223727   False      False
115198   False      False
507024   False      False
671357    True       True
502765   False      False
346679   False      False
162081   False      False
608746   False      False
235132   False      False
403942   False      False
311604   False      False
507799   False      False
672037   False      False
747084   False      False
408786   False      False
447323   False      False
527279   False      False
53068    False      False
111609   False      False
32258    False      False
424609   False      False
673959   False      False
603308   False      False
159899   False      False